### ISSUE TITLE
 @Github PR / Issue の Markdown TODO リストまだ使ってないの？え‥嘘でしょ？✋

### ISSUE THREAD

**Issue by YumaInaura** [YumaInaura/YumaInaura#79]
# 例

https://github.com/YumaInaura/YumaInaura/issues/63

![image](https://user-images.githubusercontent.com/13635059/50553726-abc45a80-0cef-11e9-86bc-d86847671bd8.png)

# 超便利

WebInputを自動的にMarkdown変換してくれる
MarkDown編集するとWebに反映してくれる、もちろん
加賀逆‥可逆！加賀逆‥可逆！加賀逆‥可逆！にんにん！

```
- [x] 心理的安全性を高める妻 
- [ ] 家族妻夫彼氏彼女友達のためのアプリケーション
- [ ] Qiita記事 1万個を目指して僕がやっていること
- [x] 量は質に転化する
- [ ] 記事の粒度は自分が決める、自分の心理
- [ ] GoogleChromeでピンどめしたい

- [ ] English suggestion keyboard inputting
- [ ] Copy and paste with current URL
- [ ] Google Chrome developer 
```

# use it

and Happy Hacking life :)

https://twitter.com/yumainaura

https://github.com/YumaInaura/YumaInaura/issues/78
